const data = {
  products: [
    {
      _id: '1',
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "/images/product-1.jpg",
      peice: 120,
      brand: "Nike",
      rating: 4.2,
      numReview: 10,
      countInStock: 0,
      description: "high quality product",
    },
    {
      _id: '2',
      name: "Adidas Fit  Shirt",
      category: "shirts",
      image: "/images/product-2.jpg",
      peice: 150,
      brand: "Adidas",
      rating: 4.5,
      numReview: 6,
      countInStock: 30,
      description: "high quality product",
    },
    {
      _id: '3',
      name: "Lacoste Free Shirt",
      category: "shirts",
      image: "/images/product-3.jpg",
      peice: 100,
      brand: "Lacoste",
      rating: 4.8,
      numReview: 4,
      countInStock: 30,
      description: "high quality product",
    },
    {
      _id: '4',
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/product-4.jpg",
      peice: 80,
      brand: "Nike",
      rating: 4.2,
      numReview: 12,
      countInStock: 30,
      description: "high quality product",
    },
    {
      _id: '5',
      name: "Puma Slim pant",
      category: "Pants",
      image: "/images/product-5.jpg",
      peice: 180,
      brand: "Puma",
      rating: 4.2,
      numReview: 13,
      countInStock: 30,
      description: "high quality product",
    },
    {
      _id: '6',
      name: "Adidas Slim pant",
      category: "Pants",
      image: "/images/product-7.jpg",
      peice: 70,
      brand: "Adidas",
      rating: 4.2,
      numReview: 30,
      countInStock: 30,
      description: "high quality product",
    },
    {
        _id: '7',
        name: "Lee Slim pant",
        category: "Pants",
        image: "/images/product-7.jpg",
        peice: 70,
        brand: "Lee",
        rating: 4.2,
        numReview: 30,
        countInStock: 30,
        description: "high quality product",
      },
  ],
};

export default data;